personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path , include

from users import views  as user_views
from django.contrib.auth import views as authentication_views

from portfolio import views

from django.conf.urls.static import static   # to click and view the image uploaded in django admin


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings       # to access information from the settings.py file

urlpatterns = [
    path('admin/', admin.site.urls),

    path('' , include('portfolio.urls') ),

    path('project/', include('project.urls')) ,

    path('register/', user_views.register , name ='register'),

    path('login/' , authentication_views.LoginView.as_view(template_name ='users/login.html') , name ='login') ,
    # above url will use an inbuilt view  (authentication_views )  above is a class based view, need to have .as_view()

    path('logout/', authentication_views.LogoutView.as_view(template_name ='users/logout.html'), name='logout') ,
    # these two views  loginview and logoutview are already created by django.  now we to build templates for these

    path('profile/' , user_views.profilepage  , name ='profile') ,

]


#urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
# necessary when working with static files

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [

    path('', views.home , name = 'home') ,

    # to add a new skill from front end
    path('add/', views.create_item ,  name='create_item' ) ,

    # to update the skills from the front end: update/id of the skill
    path('update/<int:id>/' , views.update_skill , name ='update_skill') ,

    # to delete a skill
    path('delete/<int:id>/' , views.delete_skill , name = 'delete_skill') ,



]

project/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [

    path('', views.all_project , name = 'all_project')
]

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    position = models.CharField(max_length=50)
    company = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    from_date = models.DateField()
    to_date = models.DateField(null=True , blank = True)        # blank = True - optional ; null = True - could leave it empty

    def __str__(self):
        return self.position



class Skills (models.Model):
    skill = models.CharField(max_length = 50)
    years = models.CharField(max_length = 50)
    tools = models.TextField(max_length=100 , blank = True , null = True)

    def __str__(self):
        return self.skill


class Education (models.Model):
    Degree = models.CharField(max_length=100)
    university = models.CharField(max_length=100)
    Graduation_year = models.CharField(max_length=50)

    def __str__(self):
        return self.Degree

project/models.py
from django.db import models

# Create your models here.

class Allprojecct (models.Model):
    project_name = models.CharField(max_length=50)
    project_desc = models.TextField(max_length=1000)
    project_url = models.URLField(blank = True , null = True)
    project_tech = models.TextField(max_length=500)



    def __str__(self):
        return self.project_name

users/models.py
from django.db import models

# Create your models here.

portfolio/forms.py
from django import forms

from .models import Skills

class SkillsForm (forms.ModelForm):
    class Meta:
        model = Skills
        fields =  [ 'skill'  , 'years'  , 'tools' ]

users/forms.py
from django import forms

from django.contrib.auth.models import User
 # above user model is already build into django

from django.contrib.auth.forms import UserCreationForm


 # we are creating a new form because we also want to get the email address of the user
 # when they signup. the usercreationform does not have an email field.
 # so we create a new form with email field and then inherit from usercreationform

 # create the new form
class RegisterForm(UserCreationForm):
     email = forms.EmailInput()

     class Meta:                    #  meaning that this meta class will hold info about the registrationform class above
         model = User
         fields = ['username' , 'email' , 'password1' , 'password2' ]

portfolio/views.py
from django.shortcuts import render , redirect

# Create your views here.
from portfolio.models import Project
from portfolio.models import Skills
from portfolio.models import Education
from .forms import SkillsForm



def home(request):
    projects = Project.objects.all()
    skills = Skills.objects.all()
    education = Education.objects.all()
    return render(request , 'portfolio/home.html' , {'projects' : projects , 'skills' : skills , 'education':education})


def create_item(request):
    form = SkillsForm(request.POST or None)

    if form .is_valid():
        form.save()
        return redirect('portfolio:home')


    return render(request ,  'portfolio/skills_form.html' , {'form':form})


def update_skill(request,id):
    item = Skills.objects.get(id=id)
    form = SkillsForm(request.POST or None , instance=item)     # the already existing skill should already be in the form

    if form .is_valid():
        form.save()
        return redirect('portfolio:home')

    return render(request , 'portfolio/skills_form.html' ,  {'form':form , 'item':item})



def delete_skill(request , id):
    item = Skills.objects.get(id=id)         # item we want to delete by its id    ( create an object of the Skills class )

    if request.method == 'POST':      # if it is a post method, we delete the item
        item.delete()
        return redirect('portfolio:home')

    return render(request , 'portfolio/skills_delete.html' , {'item':item} )       # to confirm the deletion

project/views.py
from django.shortcuts import render

# Create your views here.
from .models import Allprojecct


def all_project(request):
    allprojects = Allprojecct.objects.all()
    return render(request , 'project/all_project.html' , {'Allprojects' : allprojects})

users/views.py
from django.shortcuts import render , redirect
# Create your views here.
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
# we will create the form from usercreationform

#from .forms import RegisterForm
from django.contrib.auth.decorators import login_required



def register(request):
    if request.method == 'POST':       # if a post request, user clicked signup in the template
        form = UserCreationForm(request.POST)     # will have all the data that was submitted with the form
        if form.is_valid():       # check if the form data retrieved is valid
            form.save()        # save user to database
            username = form.cleaned_data.get('username')   # we want to get the name that was entered into username field from the form
            messages.success(request , f'welcome {username}, your account is created')
            return redirect('login')          # this will redirect this to the login page ( check the urls.py to see the login url)

    else:
        form  = UserCreationForm()      # if the signup button is not pressed

    return render (request ,   'users/register.html'  , {'form':form})      # we want to pass the inbuild from to the template register.html



# we want to restrict access to the profile page if user is logedout , so we add a decorator

@login_required
def profilepage(request):
    return render(request , 'users/profile.html' )

portfolio/templates/portfolio/basetemplate.html
{% load static %}     <!-- used to access the static folder  from the portfolio -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

       <!-- Bootstrap CSS -->
         <link href="{% static 'portfolio/custom.css' %}" rel="stylesheet">   <!-- to access the style sheet -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">



    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" />

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">   <!-- to include google font into the stylesheet-->



        <title> Mathews gregory</title>   <!-- will be shown in the page tab above the screen -->
</head>


<body>
 <div class="container">
    <header id="main-header">
      <div class="row no-gutters">
        <div class="col-lg-4 col-md-5">
          <img src="{% static 'portfolio/image1.jpg' %}" alt="">
        </div>

        <div class="col-lg-8 col-md-7">
          <div class="d-flex flex-column">
            <div class="p-5 bg-dark text-white">
              <div class="d-flex flex-row justify-content-between align-items-center">
                <h1 class="display-4">Mathews Gregory
                </h1>
                  <div>
                    <a  href="https://www.linkedin.com/in/mathews-gregory-595b37116/" class="text-white" >
                      <i class="fab fa-linkedin"></i>
                     </a>
                  </div>
                    <div>
                      <a href="https://github.com/mgrego03?tab=repositories" class="text-white">
                        <i class="fab fa-github"></i>
                      </a>
                    </div>
              </div>
                <div class="row justify-content-end">





                </div>
            </div>

            <div class="p-5 bg-black" >
                Data Engineer with experience in SQL , Power BI and Python-Django

            </div>



            <div class="the-blocks">
              <div class="d-flex flex-row text-white align-items-stretch text-center">   <!-- stretch , from top to bottom -->
                <div class="port-item p-5 bg-primary" data-toggle="collapse" data-target="#home">
                  <i class="fas fa-home fa-2x d-block"></i>
                 <!-- <span class="d-none d-sm-block #for-home">Home</span>-->
                  <a href ="#" class="d-none d-sm-block"> Home </a>
                </div>
                <div class="port-item p-5 bg-success" data-toggle="collapse" data-target="#resume">
                  <i class="fas fa-graduation-cap fa-2x d-block"></i>
                  <a href ="#" class="d-none d-sm-block"> Resume </a>
                </div>
                <div class="port-item p-5 bg-warning" data-toggle="collapse" data-target="#work">
                  <i class="fas fa-folder-open fa-2x d-block"></i>
                  <a href ="{% url 'project:all_project' %}" class="d-none d-sm-block"> Projects </a>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </header>


     <!-- to display any messages, will the signup message below after successfuly signed up -->
      {% if messages %}

                {% for message in messages %}
                 <div class="alert alert- {{message.tags}}">
                    {{message}}
                 </div>
                {% endfor %}
      {% endif %}




  {% block content %}       <!-- in here it will go back to the html, to check it has any block to put here -->


  {% endblock %}


       <!-- FOOTER -->




      <div class="card border-primary mb-3 bg-dark">
            <div class="card-body">

        <!--        <h4 class="card-title">
                 <a class="btn btn-outline-primary"  href ="{% static 'portfolio/New_resume.docx' %}" >  Download Resume </a>
                </h4>
  -->
            </div>
        </div>


  </div>

 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js" integrity="sha512-Y2IiVZeaBwXG1wSV7f13plqlmFOx8MdjuHyYFVoYzhyRr3nH/NMDjTBSswijzADdNzMyWNetbLMfOpIPl6Cv9g==" crossorigin="anonymous"></script>
 <script>
    $('.port-item').click(function () {
      $('.collapse').collapse('hide');
    });
</script>


</body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/basetemplate.html'%}   <!-- will send it to base_bootstrap, then check for block content-->

{% block content %}

{% load static %}

 <link href="{% static 'portfolio/custom.css' %}" rel="stylesheet">

 <!-- RESUME -->

 <div id="resume" class="collapse">
      <div class="card card-body py-5">
        <div class="row">
            {% for project in projects %}
               <div class="col-lg-4 col-md-6">
                   <div class="card-deck">
                       <div class="card">
                           <div class="card-body">
                               <h4 class="card-header" style="color: red;  font-size: 15px; " >{{project.position }}</h4>
                               <p class="card-text"  style="height:100px;">{{project.description}}</p>

                               <div class="card-footer">
                                   <h6 class="text-muted">
                                       {{project.from_date|date:'M Y'}}  <span> - </span>
                                       {% if project.to_date %}
                                       {{project.to_date|date:'M Y'}}
                                       {% else %}
                                       <strong> present </strong>
                                       {% endif %}

                                   </h6>
                               </div>
                           </div>
                       </div>
                   </div>

                </div>
            {% endfor %}
        </div>
      </div>
 </div>



<!-- home -->


 <div id="home" class="collapse show">
      <div class="card">

            {% for edu in education %}
                    <div class="card-header bg-primary">
                      Education
                    </div>
                    <div class="card-body">

                        <div class="card-text">
                           <p>  {{ edu.Degree}} <br>
                                {{ edu.university}}  <br>
                                {{ edu.Graduation_year}}   <br>
                            </p>

                        </div>
                    </div>
             {% endfor %}



          <!-- certificate image -->
          <div class="container">
              <div class="row mb-2">
                  <div class="col-md-2">
                      <a href="{% static 'portfolio/Degree.jpg' %}" data-toggle="lightbox" data-gallery="img-gallery" data-height="20"
                         data-width="20">

                         <img src="{% static 'portfolio/Degree.jpg' %}" alt="" class="img-fluid">
                      </a>
                  </div>

              </div>
          </div>
      </div>

        <div class="card-header bg-primary">
              <div class="row">
                   <div class="col-md-10">

                      My Skills
                   </div>
                   <div class="col-md-2">

                       <a href ="{% url 'portfolio:create_item'  %}" class="text-white">Add new skill </a>
                   </div>
              </div>
        </div>



      <div class="card card-body py-5">
            <div class="row">
                {% for skill in skills %}
                   <div class="col-lg-6">

                           <div class="card-deck">
                               <div class="card">
                                    <div class="card-body">
                                      <h4 class="card-text text-primary" >{{ skill.skill}}</h4>

                                      <p class="card-text" > {{skill.tools}}</p>

                                           <div class="card-footer">
                                                <h6 class="text-muted">
                                                 Years of Experience:     {{ skill.years }}

                                                </h6>
                                           </div>


                                       <a class ="btn btn-danger" href ="{% url 'portfolio:delete_skill' skill.id %}"  role="button" >Delete </a>
                                         <a class ="btn btn-warning" href ="{% url 'portfolio:update_skill' skill.id %}" role="button" > Update </a>
                                    </div>
                               </div>
                           </div>

                    </div>
                {% endfor %}
            </div>
      </div>
</div>




 <script>
    $('.port-item').click(function () {
      $('.collapse').collapse('hide');
    });
</script>


 <script>
    $(document).on('click', '[data-toggle="lightbox"]', function (event) {
      event.preventDefault();
      $(this).ekkoLightbox();
    });
</script>


{% endblock %}

portfolio/templates/portfolio/skills_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>


<form method="POST">



<div class ='container text-center'>
     {% csrf_token %}

  <h3 class="mt-3 alert alert-success">  Are you sure you want to delete {{item.skill}}</h3>

       <button type="submit"> Confirm </button>

</div>





</form>

</body>
</html>

portfolio/templates/portfolio/skills_form.html
{% load static %}     <!-- used to access the static folder  from the portfolio -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

       <!-- Bootstrap CSS -->
         <link href="{% static 'portfolio/custom.css' %}" rel="stylesheet">   <!-- to access the style sheet -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">   <!-- to include google font into the stylesheet-->


</head>


  <body>



<div class="container">
   <div class ='row'>
      <div  class ='col-md-6'>
          <div class="card">
              <div class ='card-header bg-info text-white'>
                   <div class="card-title">
                       Add/Update New Skills
                   </div>
              </div>
              <div class ='card-body'>
                  <form method="POST">
                      {% csrf_token %}
                     {% for field in form %}
                          <div class="form-group">

                              {{field.name }} <span> :</span>
                              {{field}}
                          </div>

                        {% endfor %}

                         <button class ='btn-info' type="submit">Save</button>

                  </form>

              </div>
          </div>
      </div>
   </div>
</div>







</body>

project/templates/project/all_project.html
{% load static %}

 <link href="{% static 'portfolio/custom.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<div class="p-3">
    <h3 class="text-center bg-dark text-white p-1"> Projects</h3>

</div>




<div class="card card-body p-5">
      <div class="card">

         {% for project in Allprojects %}
            <div class="card-header bg-primary text-white">
             {{ project.project_name}}
            </div>
            <div class="card-body">

                <p class="card-text">
                 {{ project.project_desc}}
                </p>


                  <p class="card-footer p-1  bg-dark text-white">
                 {{ project.project_tech}}
                </p>


            {% if project.project_url %}                         <!--   if project.url exist then display the a tag   Link  -->
                <a class="btn btn-success" href="{{ project.project_url }}">                              <!-- you can provide the destination link in the django admin site -->
                  link to Github
                </a>

            {% endif %}


            </div>


         {% endfor %}
       </div>

</div>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>

<div class="container">
   <div class ='row'>
      <div  class ='col-md-4 offset-md-4'>
          <div class="card">
              <div class ='card-header bg-info text-white'>
                   <div class="card-title">
                       Login
                   </div>
              </div>
              <div class ='card-body'>

                    <form method ='POST'>
                            {% csrf_token %}

                             {{ form }}

                        <!-- the form above , is coming from  authentication_views.LoginView .  ( this is not the registration form)  -->
                        <button  class='btn-primary mt-1' type="submit">Login</button>
                    </form>
              </div>
          </div>
      </div>
   </div>
</div>


</body>
</html>

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>


<div class ='container text-center'>
     {% csrf_token %}

  <h3 class="mt-3 alert alert-Warning">  You are being logged out</h3>



</div>




</body>
</html>

users/templates/users/profile.html
{% load static %}     <!-- used to access the static folder  from the portfolio -->


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
                  <link href="{% static 'portfolio/custom.css' %}" rel="stylesheet">   <!-- to access the style sheet -->

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>



<div class="container">
 <div class="row" >
      <div class="card" style="width: 20rem;">
            <div class="card-body bg-dark text-white">
               <!--    <img class="card-img-top" src="https://source.unsplash.com/random/300x200" alt="">  -->
                 <img class="image2" src="{% static 'portfolio/image2.jpg' %}"  alt="">
                <h4 class="card-title "> Mathews Gregory</h4>
                <h6 class="card-subtitle text-muted">Developer</h6>
                <p class="card-text "> Education : MS in Computer Science
                 Citizenship : US </p>

            </div>
      </div>

      <div class="card" style="width: 40rem;">
            <div class="card-body">
                <h4 class="card-title bg-dark text-white"> Welcome {{ user.username }} , to MyProfile page.  </h4>

                <p class="card-text"> <p>Born and raised in India. Came to United States with my family when i was 15. Graduated from
                New York Institute of technology with MS.Computer Science. </p>

                  <p>Currently working as a Developer at Jzanus, a Health Care Revenue Cycle Management Company. Priority of the work includes Designing
                    and testing Database Queries. Resolve Production Issues. Create new procedures and jobs for reporting and data importing. Utilized
                      python for predictive analysis and machine learning to reduce manual task. </p>

                 <p>  Have developed Django/python application. Trying to learn React.js during my free time. </p>

            </div>
      </div>

 </div>
</div>
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


</head>
<body>







<div class="container">
   <div class ='row'>
      <div  class ='col-md-4 offset-md-4'>
          <div class="card">
              <div class ='card-header bg-info text-white'>
                   <div class="card-title">
                       Register
                   </div>
              </div>
              <div class ='card-body'>

                    <form method ='POST'>
                        {% csrf_token %}
                      <!-- we need to access the  individual fields from this form   {{ form }}   , using the for loop as below -->

                       {% for field in form %}
                                <div class="form-group">
                                    {{field.name}}
                                     <br>
                                    {{field}}
                                </div>
                            {% endfor %}


                        <!-- the form above , is coming from  authentication_views.LoginView .  ( this is not the registration form)  -->
                        <button  class='btn-info' type="submit">Signup</button>
                    </form>
              </div>
          </div>
      </div>
   </div>
</div>




</body>
</html>